my_db_params:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: foo
    database_user: root
    database_password: null

my_mailer_params:
    mailer_transport: smtp
    #......

